#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightFront,    tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************/
/* Imports the Debuggar Window,allowing for values to be displayed */
/* while the Robot is running																			 */
/*  !!!!!  MUST HAVE THE USB -> CONTROLLER ADAPTER TO WORK  !!!!!  */
/*******************************************************************/

#pragma DebuggerWindows("DebugStream")


// PID using optical shaft encoder
//
// Shaft encoder has 360 pulses per revolution
//

/*************************/
/* ----- CONSTANTS ----- */
/*************************/

#define PID_SENSOR_INDEX_L		leftEncoder
#define PID_SENSOR_INDEX_R    rightEncoder
#define PID_SENSOR_SCALE      1

#define PID_MOTOR_INDEX_L			leftFront
#define PID_MOTOR_INDEX_R     rightFront
#define PID_MOTOR_SCALE       -1

#define PID_DRIVE_MAX       127
#define PID_DRIVE_MIN     (-127)

#define PID_INTEGRAL_LIMIT  50


/********************/
/* -- PID VALUES -- */
/********************/

//"K" tells us it's a constant value, and should not be changed insidee the code
float  pid_Kp = 0.5;
float  pid_Ki = 0.00;
float  pid_Kd = 0.0;

static int   pidRunning = 1;
static float pidRequestedValue;


/********************************/
/* ---------------------------- */
/* --- USER CONTROL METHODS --- */
/* ---------------------------- */
/********************************/

//Sets the set point on the encoders by inches
//In goes # of inches, out comes encoder value
void setDriveDistance(float distance) {
	//Sets the setpoint on the encoder
	pidRequestedValue = distance * 585;
}

//Sets the set point on the encoders by rotations
//In goes # of rotations, out comes encoder value
void setDriveRotation(float rotations) {
	//Sets the setpoint on the encoder
	pidRequestedValue = (rotations * 12.4) * 53.5;
}


/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  pid control task                                                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task pidController() {
	float  pidSensorCurrentValue;

	float  pidError;
	float  pidLastError;
	float  pidIntegral;
	float  pidDerivative;
	float  pidDrive;

	// If we are using an encoder then clear it
	if( SensorType[ PID_SENSOR_INDEX_R ] == sensorQuadEncoderOnI2CPort &&
		SensorType[ PID_SENSOR_INDEX_L ] == sensorQuadEncoderOnI2CPort) {
		SensorValue[ PID_SENSOR_INDEX_R ] = 0;
		SensorValue[ PID_MOTOR_INDEX_L ] = 0;
	}

	// Init the variables
	pidLastError  = 0;
	pidIntegral   = 0;

	while( true ) {
		// Is PID control active ?
		if( pidRunning ) {
			// Read the sensor value and scale
			pidSensorCurrentValue = SensorValue[ PID_SENSOR_INDEX_R ] * PID_SENSOR_SCALE;
			pidSensorCurrentValue = -1 * (SensorValue[ PID_SENSOR_INDEX_L ] * PID_SENSOR_SCALE);

			// calculate error
			pidError = pidSensorCurrentValue - pidRequestedValue;

			// integral - if Ki is not 0
			if( pid_Ki != 0 ) {
				// If we are inside controlable window then integrate the error
				if( abs(pidError) < PID_INTEGRAL_LIMIT ) {
					pidIntegral = pidIntegral + pidError;
					} else {
					pidIntegral = 0;
				}
				} else {
				pidIntegral = 0;
			}

			// calculate the derivative
			pidDerivative = pidError - pidLastError;
			pidLastError  = pidError;

			// calculate drive
			pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

			// limit drive
			if( pidDrive > PID_DRIVE_MAX )
				pidDrive = PID_DRIVE_MAX;
			if( pidDrive < PID_DRIVE_MIN )
				pidDrive = PID_DRIVE_MIN;

			// send to motor
				//sets speed of the motor
			motor[ PID_MOTOR_INDEX_R ] = pidDrive * PID_MOTOR_SCALE;
			motor[ backRight] = pidDrive * PID_MOTOR_SCALE;
			motor[ PID_MOTOR_INDEX_L ] = pidDrive * PID_MOTOR_SCALE;
			motor[ backLeft] = pidDrive * PID_MOTOR_SCALE;
			} else {
			// clear all
			pidError      = 0;
			pidLastError  = 0;
			pidIntegral   = 0;
			pidDerivative = 0;
			motor[ PID_MOTOR_INDEX_R ] = 0;
			motor[ PID_MOTOR_INDEX_L ] = 0;
		}

		// Run at 50Hz
		wait1Msec( 25 );
	}
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  main task                                                                  */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task main() {

	// send the motor off somewhere
	// 640 = 1 rotation
	// 1 rotation = 12.4in

  setDriveDistance(5);
  //setDriveRotation(6);
	//pidRequestedValue = 1920;

	// start the PID task
	startTask( pidController );

	// use joystick to modify the requested position
	while( true ) {
		// maximum change for pidRequestedValue will be 127/4*20, around 640 counts per second
		// free spinning motor is 100rmp so 1.67 rotations per second
		// 1.67 * 360 counts is 600

		//Sets the setpoint on the encoder
	/*
		if(vexRT[ Ch2 ]/4 > 0.1) {
			pidRequestedValue = pidRequestedValue + (vexRT[ Ch2 ]/4);
		}
		*/

		// Prints the encoder values
		writeDebugStreamLine("Right Encoder: %d", SensorValue(PID_SENSOR_INDEX_R));
		writeDebugStreamLine("Left Encoder: %d", SensorValue(PID_SENSOR_INDEX_L));

		wait1Msec(50);


	}

}
